# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-22 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0002_auto_20200622_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='short_body',
            field=models.TextField(max_length=2000),
        ),
    ]
