# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-25 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200622_2358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='full_body',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='post',
            name='short_body',
        ),
    ]
